name: acceso de fortaleza 

on: push

jobs:
  acceso-a-la-base:
    runs-on: ubuntu-latest
    steps:
      - name: agente llega a la fortaleza
        run: |
          echo "Agente ${{ github.actor }} ha llegado a la fortaleza"
          echo ""
          echo "buscar archivos de la legion del mal"
          ls -la
          echo ""
          echo "pero que paso no hay nada"
      - name: "llega brianiac y les da acceso a la fortaleza"
        uses: actions/checkout@v4
      - name: "ahora si vamos a ver los planes
          de la legion del mal"
        run: |
          echo "ahora si vamos a ver los archivos de la legion del mal"
          ls -la
          echo "si funciona"
          echo ""
          echo "planes:"
          ls planes/
          echo "miembros:"
          ls miembros/
          echo "inteligencia:"
          ls inteligencia/

