name: reclutamiento de agente 

on: push

jobs:
    report-de-reclutamiento:
      runs-on: ubuntu-latest  
      steps:
        - name: agente se presenta
          run: echo "Hola, soy lex luthor , lider del la legion del mal"
        - name : reporte de identidad
          run: |
            echo "reporte identidad"
            echo "================"
            echo ""
            echo "contexto de github"
            echo "repo: ${{ github.repository }}"
            echo "operacion: ${{ github.sha }}"
            echo "metadata: ${{ toJSON(github) }}"
            
